#!/usr/bin/expect

set timeout 30
set host "bandit.labs.overthewire.org"
set username "bandit0"
set password "bandit0"
set port "2220"
set local_script "bandit0_sol.sh"

spawn scp -P $port $local_script $username@$host:/tmp/
expect {
    "password:" {
        send "$password\r"
    }
    "yes/no" {
        send "yes\r"
        expect "password:"
        send "$password\r"
    }
}
expect eof




spawn ssh $username@$host -p $port
expect {
    "password:" {
        send "$password\r"
    }
    "yes/no" {
        send "yes\r"
        expect "password:"
        send "$password\r"
    }
}


send "chmod +x /tmp/bandit0_sol.sh\r"
expect "$ "
send "/tmp/bandit0_sol.sh\r"
expect "$" 
interact
